version: '3'
services:
  cpp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./CppND-Route-Planning-Project:/CppND-Route-Planning-Project
      - ./scripts/build-project.sh:/build-project.sh
    command: >
      bash -c "
      chmod +x /build-project.sh &&
      /build-project.sh
      "
